#' Package-level imports and global-variable registrations
#'
#' Imports the base-R helpers used across the package and registers the
#' non-standard-evaluation column names referenced inside dplyr pipelines, so
#' `R CMD check` does not flag them as undefined globals. This file defines no
#' runtime behaviour.
#'
#' @importFrom stats approx mad median setNames
#' @importFrom utils flush.console head
#' @importFrom rlang .data :=
#' @keywords internal
#' @name avpipeline-globals
NULL

utils::globalVariables(c(
  ".",
  "adjusted_close",
  "ask",
  "ask_size",
  "atm_iv",
  "atm_iv_call",
  "atm_iv_put",
  "atm_strike",
  "bid",
  "bid_size",
  "capitalExpenditures_ttm_per_share",
  "capitalLeaseObligations_per_share",
  "cashAndShortTermInvestments_per_share",
  "commonStockSharesOutstanding",
  "contractID",
  "cum_split_factor",
  "data_type",
  "days_to_expiration",
  "delta",
  "depreciationAndAmortization_ttm_per_share",
  "depreciation_ttm_per_share",
  "dividend_amount",
  "ebit_ttm_per_share",
  "effective_date",
  "effective_shares_outstanding",
  "expiration",
  "fiscalDateEnding",
  "fiscal_month",
  "fiscal_year",
  "has_balance_sheet",
  "has_cash_flow",
  "has_complete_financial_data",
  "has_financial_data",
  "has_income_statement",
  "high",
  "implied_volatility",
  "in_all_three",
  "in_balance_sheet",
  "in_cash_flow",
  "in_income_statement",
  "industry",
  "last",
  "longTermInvestments_per_share",
  "low",
  "mark",
  "max_auth_date",
  "moneyness",
  "n",
  "needs_price",
  "needs_quarterly",
  "open_interest",
  "operatingCashflow_ttm_per_share",
  "overview_days_stale",
  "overview_last_fetched_at",
  "post_filing_split_multiplier",
  "previous_close",
  "price_days_stale",
  "price_last_date",
  "quarterly_days_stale",
  "quarterly_last_fetched_at",
  "reportTime",
  "reportedCurrency",
  "reportedDate",
  "rho",
  "shortLongTermDebtTotal_per_share",
  "split_coefficient",
  "split_factor",
  "status",
  "strike",
  "strike_call",
  "strike_put",
  "subsector",
  "symbol",
  "theta",
  "ticker",
  "totalAssets_per_share",
  "totalRevenue_ttm_per_share",
  "totalShareholderEquity_per_share",
  "type",
  "valid_shares",
  "vega",
  "volume",
  "week_start"
))
